### ISSUE TITLE
ImportError: cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by TCLW123** [mit-han-lab/distrifuser#24]
Traceback (most recent call last):
  File "/home/xinyihu/distrifuser-main/scripts/sdxl_example.py", line 3, in <module>
    from distrifuser.pipelines import DistriSDXLPipeline
  File "/home/distrifuser-main/distrifuser/pipelines.py", line 2, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionXLPipeline, UNet2DConditionModel
  File "/home/anaconda3/envs/distifusion/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/anaconda3/envs/distifusion/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/anaconda3/envs/distifusion/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/anaconda3/envs/distifusion/lib/python3.10/site-packages/huggingface_hub/__init__.py)

The above error occurred while I was running example.
My configuration is NVIDIA 4090+Python 3.10+Pytorch2.2.0+cu121  CUDA Version: 12.2

**Comment by TCLW123** [comment]
I solved this problem by demoting huggingface_hub from 0.26.0 to 0.23.2
